CREATE DATABASE IF NOT EXISTS TESTDB
DEFAULT CHARACTER SET UTF8
COLLATE utf8_bin;

CREATE TABLE IF NOT EXISTS TESTDB.HIEN (
  `ID` varchar(36) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TESTDB.TEST_TABLE(
-- unique: KHONG TRUNG DATA, auto_increment: TU TANG
ID INT unique auto_increment NOT NULL,
NAME varchar(255),
PHONE VARCHAR(255),
ADDRESS VARCHAR(255),
TYPE VARCHAR(1) DEFAULT 'S',
Cre_date datetime,
primary key (id)); 


-- drop DATABASE testdb;